// Generated by hand to mirror Rcpp::compileAttributes() output.
// After modifying rcpp_bindings.cpp, regenerate by running
//     Rcpp::compileAttributes("r/aompls")
// inside R.

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

Rcpp::List aompls_fit_cpp(Rcpp::NumericMatrix X, Rcpp::NumericVector y,
                          int max_components, int n_folds, std::string cv_mode,
                          bool one_se_rule, bool center, double random_state,
                          std::string preproc, int osc_n_components,
                          double asls_lam, double asls_p, int asls_n_iter,
                          Rcpp::Nullable<Rcpp::List> external_folds);

RcppExport SEXP _aompls_aompls_fit_cpp(SEXP XSEXP, SEXP ySEXP, SEXP max_componentsSEXP,
                                       SEXP n_foldsSEXP, SEXP cv_modeSEXP, SEXP one_se_ruleSEXP,
                                       SEXP centerSEXP, SEXP random_stateSEXP, SEXP preprocSEXP,
                                       SEXP osc_n_componentsSEXP, SEXP asls_lamSEXP,
                                       SEXP asls_pSEXP, SEXP asls_n_iterSEXP,
                                       SEXP external_foldsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter<Rcpp::NumericMatrix>::type X(XSEXP);
    Rcpp::traits::input_parameter<Rcpp::NumericVector>::type y(ySEXP);
    Rcpp::traits::input_parameter<int>::type max_components(max_componentsSEXP);
    Rcpp::traits::input_parameter<int>::type n_folds(n_foldsSEXP);
    Rcpp::traits::input_parameter<std::string>::type cv_mode(cv_modeSEXP);
    Rcpp::traits::input_parameter<bool>::type one_se_rule(one_se_ruleSEXP);
    Rcpp::traits::input_parameter<bool>::type center(centerSEXP);
    Rcpp::traits::input_parameter<double>::type random_state(random_stateSEXP);
    Rcpp::traits::input_parameter<std::string>::type preproc(preprocSEXP);
    Rcpp::traits::input_parameter<int>::type osc_n_components(osc_n_componentsSEXP);
    Rcpp::traits::input_parameter<double>::type asls_lam(asls_lamSEXP);
    Rcpp::traits::input_parameter<double>::type asls_p(asls_pSEXP);
    Rcpp::traits::input_parameter<int>::type asls_n_iter(asls_n_iterSEXP);
    Rcpp::traits::input_parameter<Rcpp::Nullable<Rcpp::List>>::type external_folds(external_foldsSEXP);
    rcpp_result_gen = Rcpp::wrap(aompls_fit_cpp(X, y, max_components, n_folds, cv_mode,
                                                one_se_rule, center, random_state, preproc,
                                                osc_n_components, asls_lam, asls_p, asls_n_iter,
                                                external_folds));
    return rcpp_result_gen;
END_RCPP
}

Rcpp::NumericVector aompls_predict_cpp(Rcpp::List model, Rcpp::NumericMatrix X);

RcppExport SEXP _aompls_aompls_predict_cpp(SEXP modelSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter<Rcpp::List>::type model(modelSEXP);
    Rcpp::traits::input_parameter<Rcpp::NumericMatrix>::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(aompls_predict_cpp(model, X));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_aompls_aompls_fit_cpp",     (DL_FUNC) &_aompls_aompls_fit_cpp,     14},
    {"_aompls_aompls_predict_cpp", (DL_FUNC) &_aompls_aompls_predict_cpp,  2},
    {NULL, NULL, 0}
};

RcppExport void R_init_aompls(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
