# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aompls_fit_cpp <- function(X, y, max_components, n_folds, cv_mode, one_se_rule, center, random_state, preproc, osc_n_components, asls_lam, asls_p, asls_n_iter, external_folds) {
    .Call(`_aompls_aompls_fit_cpp`, X, y, max_components, n_folds, cv_mode, one_se_rule, center, random_state, preproc, osc_n_components, asls_lam, asls_p, asls_n_iter, external_folds)
}

aompls_predict_cpp <- function(model, X) {
    .Call(`_aompls_aompls_predict_cpp`, model, X)
}

