## Parity tests against the JSON fixtures generated by
## scripts/export_reference.py (Python AOM_v0 reference).
##
## We resolve the reference directory via the AOMPLS_REF_DIR env var (set by
## the runner) or relative paths from the source tree. testthat tests skip
## when the fixtures are unavailable rather than fail.

skip_if_not_installed("jsonlite")

resolve_ref_dir <- function() {
  env <- Sys.getenv("AOMPLS_REF_DIR", unset = "")
  if (nzchar(env) && dir.exists(env)) return(normalizePath(env))
  ## Walk up from the testthat dir to bench/AOM_lib/cpp/tests/reference.
  candidates <- c(
    file.path(getwd(), "..", "..", "..", "..", "cpp", "tests", "reference"),
    file.path(getwd(), "..", "..", "cpp", "tests", "reference"),
    "/home/delete/nirs4all/nirs4all/bench/AOM_lib/cpp/tests/reference"
  )
  for (c in candidates) if (dir.exists(c)) return(normalizePath(c))
  return("")
}

ref_dir <- resolve_ref_dir()
datasets <- c("BEER", "CORN", "ALPINE")
cases <- list(
  list(name = "kfold5",       one_se = FALSE),
  list(name = "kfold5_oneSE", one_se = TRUE),
  list(name = "spxy5",        one_se = FALSE)
)

for (ds in datasets) {
  ref_path <- file.path(ref_dir, paste0(ds, ".json"))
  for (case in cases) {
    case_name <- case$name
    test_that(paste(ds, case_name, "parity"), {
      if (!nzchar(ref_dir) || !file.exists(ref_path))
        skip(paste("reference fixture not found:", ref_path))
      ## simplifyVector=FALSE so fold_test_indices stays a list of vectors
      ## (otherwise jsonlite collapses equally-sized folds into a matrix).
      ref <- jsonlite::fromJSON(ref_path, simplifyVector = FALSE)
      c_ref <- ref[[case_name]]
      X <- matrix(unlist(c_ref$X), nrow = length(c_ref$X), byrow = TRUE)
      y <- as.numeric(unlist(c_ref$y))
      folds <- lapply(c_ref$fold_test_indices, function(v) as.integer(unlist(v)))
      m <- aom_pls(X, y,
                   max_components = as.integer(c_ref$max_components),
                   cv_mode = "external",
                   external_folds = folds,
                   one_se_rule = case$one_se,
                   random_state = 0L)
      expect_equal(m$selected_operator_name, c_ref$selected_operator_name)
      expect_equal(as.integer(m$selected_operator_index),
                   as.integer(c_ref$selected_operator_index))
      expect_equal(as.integer(m$n_components_selected),
                   as.integer(c_ref$n_components_selected))
      expect_lt(max(abs(m$coef - as.numeric(unlist(c_ref$coef)))), 1e-8)
      expect_lt(abs(m$intercept - c_ref$intercept), 1e-8)
      pred <- predict(m, X)
      expect_lt(max(abs(pred - as.numeric(unlist(c_ref$predictions_train)))), 1e-8)
    })
  }
}
