## Generated by hand to avoid running compileAttributes() at install time.
## After modifying src/rcpp_bindings.cpp, run inside R:
##    Rcpp::compileAttributes("r/aompls")
## to regenerate this file along with src/RcppExports.cpp.

aompls_fit_cpp <- function(X, y, max_components, n_folds, cv_mode, one_se_rule,
                           center, random_state, preproc, osc_n_components,
                           asls_lam, asls_p, asls_n_iter, external_folds) {
  .Call("_aompls_aompls_fit_cpp", X, y, max_components, n_folds, cv_mode,
        one_se_rule, center, random_state, preproc, osc_n_components,
        asls_lam, asls_p, asls_n_iter, external_folds, PACKAGE = "aompls")
}

aompls_predict_cpp <- function(model, X) {
  .Call("_aompls_aompls_predict_cpp", model, X, PACKAGE = "aompls")
}
