function test_parity()
%TEST_PARITY  Parity gate for the MATLAB MEX wrapper against the JSON fixtures.
%
%   Requires:
%     - MATLAB with the MEX wrapper built (aompls_mex)
%     - The JSON parity fixtures under ../cpp/tests/reference/<DATASET>.json
%       (generated by ../scripts/export_reference.py)
%
% Usage: from the matlab/ directory, run `test_parity()`.

datasets = {'BEER', 'CORN', 'ALPINE'};
cases = {struct('name', 'kfold5', 'one_se', false), ...
         struct('name', 'kfold5_oneSE', 'one_se', true), ...
         struct('name', 'spxy5', 'one_se', false)};

fails = 0;
ref_dir = fullfile(fileparts(mfilename('fullpath')), '..', 'cpp', 'tests', 'reference');
for d = 1:numel(datasets)
    ds = datasets{d};
    ref_path = fullfile(ref_dir, [ds, '.json']);
    if ~exist(ref_path, 'file')
        warning('aompls:test', 'missing fixture: %s', ref_path);
        continue
    end
    raw = jsondecode(fileread(ref_path));
    for c = 1:numel(cases)
        case_name = cases{c}.name;
        ref = raw.(case_name);
        X = double(ref.X);
        y = double(ref.y);
        folds = cell(1, numel(ref.fold_test_indices));
        for k = 1:numel(ref.fold_test_indices)
            folds{k} = double(ref.fold_test_indices{k});
        end
        opts = struct('max_components', ref.max_components, ...
                      'cv_mode', 'external', ...
                      'external_folds', {folds}, ...
                      'one_se_rule', cases{c}.one_se, ...
                      'random_state', 0);
        m = aom_pls(X, y, opts);
        tag = sprintf('[%s/%s]', ds, case_name);
        if ~strcmp(m.selected_operator_name, ref.selected_operator_name)
            fprintf(2, 'FAIL %s op (matlab=%s, ref=%s)\n', tag, m.selected_operator_name, ref.selected_operator_name);
            fails = fails + 1;
            continue
        end
        if m.n_components_selected ~= double(ref.n_components_selected)
            fprintf(2, 'FAIL %s k (matlab=%d, ref=%d)\n', tag, m.n_components_selected, ref.n_components_selected);
            fails = fails + 1;
            continue
        end
        coef_diff = max(abs(m.coef - double(ref.coef)));
        if coef_diff > 1e-8
            fprintf(2, 'FAIL %s coef |Delta|=%.3e\n', tag, coef_diff);
            fails = fails + 1;
            continue
        end
        pred = aom_pls_predict(m, X);
        pred_diff = max(abs(pred - double(ref.predictions_train)));
        if pred_diff > 1e-8
            fprintf(2, 'FAIL %s pred |Delta|=%.3e\n', tag, pred_diff);
            fails = fails + 1;
            continue
        end
        fprintf('%s OK selected=%s k=%d coef|D|=%.3e pred|D|=%.3e\n', ...
                tag, m.selected_operator_name, m.n_components_selected, coef_diff, pred_diff);
    end
end
if fails == 0
    fprintf('test_parity: ALL PASS\n');
else
    error('aompls:test', 'test_parity: %d failure(s)', fails);
end
end
